export default function () {
    return [
    {	id: 1,
      name: 'Greenpeace Philippines',
      description: 'An active volunteer organization that campaigns for their mission to save the environment.',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:false}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:false},
              {name:'Background in Science and Technology', val:true}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:true}, {name:'Community Development', val:false}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:false}],
      startdate: '12 November 2017',
      enddate: '12 May 2018'
    },

    {	id: 2,
      name: 'Volunteer Youth Leaders for Health-Philippines',
      description: 'A service-oriented organization that aims to empower the Filipino Youth for health.',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:true}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:true},
              {name:'Background in Science and Technology', val:false}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:false}, {name:'Community Development', val:true}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:false}],
      startdate: '22 October 2017',
      enddate: '22 April 2018'
    },

    {	id: 3,
      name: 'Love Yourself',
      description: 'A volunteer organization for the youth and the LGBT-MSM that aims to promote loving oneself.',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:true}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:true},
              {name:'Background in Science and Technology', val:false}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:false}, {name:'Community Development', val:true}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:true}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:false}],
      startdate: '05 Jan 2018',
      enddate: '05 July 2018'
    },

    {	id: 4,
      name: 'PinoyME Foundation',
      description:'Started out as a social consortium to support the growth of Microfinance Institution (MFIs) before becoming a social investment banker for microentrepreneurs.',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:false}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:false},
              {name:'Background in Science and Technology', val:true}, {name:'Background in Business Management/Economics', val:true}],
      interests:[{name:'Environmental Work', val:false}, {name:'Community Development', val:true}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:false}],
      startdate: '09 February 2018',
      enddate: '09 August 2018'
    },

    {	id: 5,
      name: 'United Nations World Food Programme',
      description: 'the leading humanitarian organization which addresses the issue of hunger.',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:false}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:true},
              {name:'Background in Science and Technology', val:false}, {name:'Background in Business Management/Economics', val:true}],
      interests:[{name:'Environmental Work', val:false}, {name:'Community Development', val:true}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:false}],
      startdate: '10 March 2018',
      enddate: '10 September 2018'
    },

    {	id: 6,
      name: 'Philippine Animal Welfare Society (PAWS)',
      description: 'a registered nonprofit organization which is dedicated to protect and promote humane treatment of all animals.',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:false}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:false},
              {name:'Background in Science and Technology', val:true}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:false}, {name:'Community Development', val:false}, {name:'Animal Rights', val:true},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:false}],
      startdate: '10 May 2018',
      enddate: '10 July 2018'
    },

    {	id: 7,
      name: 'Amnesty International',
      description: 'a non-profit organization with a global movement to let all people enjoy human rights. It has programs for Human Rights Education and Activism and Mobilization for its activist members.',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:true}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:false},
              {name:'Background in Science and Technology', val:false}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:false}, {name:'Community Development', val:true}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:true}, {name:'Women Empowerment', val:true}, {name:'Education and Literacy', val:false}],
      startdate: '23 August 2018',
      enddate: '12 October 2018'
    },

    {	id: 8,
      name: 'Gawad Kalinga',
      description: 'a movement whose mission is to eradicate poverty for 5 millions families, and restoring the human dignity of the poor.',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:true}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:false},
              {name:'Background in Science and Technology', val:false}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:false}, {name:'Community Development', val:true}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:false}],
      startdate: '23 August 2018',
      enddate: '12 October 2018'
    },

    { id: 9,
      name: 'Haribon Foundation',
      description: 'an organiztion that commits to helping through nature conservation. It is known with their services such as conserving sites and habitats, saving species, encouraging sustainability, and empowering people',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:true}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:false},
              {name:'Background in Science and Technology', val:false}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:true}, {name:'Community Development', val:true}, {name:'Animal Rights', val:true},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:false}],
      startdate: '12 February 2018',
      enddate: '18 May 2018'
    },

    { id: 10,
      name: 'World Wildlife Fund Philippines (WWF)',
      description: 'an organizaation focused on addressing the issues on the Philippine environment as they also want to live in harmony',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:true}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:false},
              {name:'Background in Science and Technology', val:false}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:true}, {name:'Community Development', val:true}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:false}],
      startdate: '12 March 2018',
      enddate: '15 June 2018'
    },

    { id: 11,
      name: 'Philippine Red Cross',
      description: 'an organization in the Philippines which aim to help people through different services such as national blood, disaster management, safety, health, social, and youth services.',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:false}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:true},
              {name:'Background in Science and Technology', val:false}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:false}, {name:'Community Development', val:true}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:false}],
      startdate: '04 June 2018',
      enddate: '07 September 2018'
    },

    { id: 12,
      name: 'World Visions Philippines',
      description: 'a Christian humanitarian organization that helps children, families and communities to alleviate proverty and social injustices.',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:true}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:false},
              {name:'Background in Science and Technology', val:false}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:false}, {name:'Community Development', val:true}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:true}],
      startdate: '18 June 2018',
      enddate: '21 September 2018'
    },

    { id: 13,
      name: 'Gentle Hands',
      description: 'an established child and youth welfare agency as the front lines of rescue and rehabilitatin of the medical, social and educational needs of at-risk children and youth. ',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:true}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:true},
              {name:'Background in Science and Technology', val:false}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:false}, {name:'Community Development', val:true}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:true}],
      startdate: '09 July 2018',
      enddate: '12 October 2018'
    },

    { id: 14,
      name: 'Habitat for Humanity',
      description: 'a leader in in answering the issues of proverty in over 70 countries and has helped more than 6.8 million people find strength, stability, and independence through safe, decent, and affordable shelter.',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:true}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:false},
              {name:'Background in Science and Technology', val:false}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:false}, {name:'Community Development', val:true}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:true}],
      startdate: '16 July 2018',
      enddate: '19 October 2018'
    },

    { id: 15,
      name: 'Virlanie Foundation',
      description: 'an organization that cares for the children who needs special protection. This includes those who are among the poor, the abandoned, the abused, exploited, neglected, and orphaned.',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:true}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:false},
              {name:'Background in Science and Technology', val:false}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:false}, {name:'Community Development', val:true}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:true}],
      startdate: '13 August 2018',
      enddate: ' 16 November 2018'
    },

    { id: 16,
      name: 'ChildHope Philippines',
      description: 'a non-profit, non-politics, non-sectaria organization who advocates for the cause of the street children in the country.',
      skills:[{name:'Project Management', val: true}, {name: 'Presentation Skills', val:true},
              {name:'Background in Psychology/Humanities', val:true}, {name:'Background in Healthcare Management/Medicine/Nutrition', val:false},
              {name:'Background in Science and Technology', val:false}, {name:'Background in Business Management/Economics', val:false}],
      interests:[{name:'Environmental Work', val:false}, {name:'Community Development', val:true}, {name:'Animal Rights', val:false},
              {name:'LGBT Rights and Issues', val:false}, {name:'Women Empowerment', val:false}, {name:'Education and Literacy', val:true}],
      startdate: '17 September 2018',
      enddate: '14 December 2018'
    }
  ]
}
